### ISSUE TITLE
Problem (small swarms)

### ISSUE THREAD

**Issue by mileswalken** [kzahel/jstorrent-legacy-app#13]
Have had this program for a while. I just got the paid version and it doesnt work anymore. Everytime I add a torrent now. . . .

Under Completion Percentage it says NaN%

and then nothing happens.

**Comment by kzahel** [comment]
Sorry you're having problems...
So there's a couple of things you'll need to check...
1. Make sure there are no notifications near the clock... (errors will be shown there)
2. Make sure the "Trackers" tab shows a number in the response column
3. Make sure there is data in the "Swarm" tab
4. Finally, take a look at "Peers" and you should see peers connecting and data being received there

Let me know how far it got in these steps.

**Comment by mileswalken** [comment]
1. Only Notification is that jstorrent has started a download. 
2. Trackers: There are 5 under urls. 2 of them have a 1 under errors. 3 of them have a 1 under seeders. All others are 0s
3. Swarm: Shows a host. Port also. Under connection results it shows -102
4. Peers has nothing. Randomly it kind of flashes overall nothing there.

**Comment by mileswalken** [comment]
And it was working perfect before the update after that i got nothing.

**Comment by kzahel** [comment]
It sounds like very weak swarms, only 1 seeder? Do you have any success with other torrents?

**Comment by drstephen** [comment]
I have tried this on stable, beta and dev doesn't work.   Have tried it with many torrents doesn't work.  Before update worked perfectly.  Now nothing, Same message every time on Trackers:   1 announce  1 error   1 timeout

Really liked this app before but now completely useless.

**Comment by kzahel** [comment]
When you say before the update, do you mean the very old version that you had to download the files and then click on "download" again in the files tab to save them to your actual hard drive?

Are you able to have any success with any other trackers/torrent sites?

**Comment by drstephen** [comment]
Yes the very old version when you had to go to the file tab and save the
fie to your hard drive by downloading again.  I have tried over 20
different sites including Ubuntu torrent and none will download.  The error
is always the same that I posted.  Is it possible to install the "very old
version"?  Thanks.

---

Stephen Gardner
Founder
Paradise TEFL
stephen@paradisetefl.comhttps://mail.google.com/mail/u/0/?view=cm&fs=1&tf=1&to=stephen@paradisetefl.com
http://paradisetefl.com

**Comment by kzahel** [comment]
It should be fixed now. Also you can just click on "Add" and then browse for a torrent file.

**Comment by drstephen** [comment]
Hi Kyle,

Still can't get JStorrent to work  :-(    Every torrent says the same
"Cannot find peers"  --- use the same torrent on utorrent or transmission
works great.  Any ideas would be appreciated.  Thanks so much.

Take care,
Stephen

---

Stephen Gardner
Founder
Paradise TEFL
stephen@paradisetefl.comhttps://mail.google.com/mail/u/0/?view=cm&fs=1&tf=1&to=stephen@paradisetefl.com
http://paradisetefl.com

**Comment by kzahel** [comment]
Can you try disabling DHT for the other clients (utorrent/transmission)
JSTorrent has no DHT support, so if you have no trackers, it will not work
I am planning on adding DHT support in the future, but it is a significant undertaking

**Comment by drstephen** [comment]
Thanks Kyle, I am sure that is the problem -- it must be DHT.  I will just
wait until JStorrent supports DHT.  :-)

---

Stephen Gardner
Founder
Paradise TEFL
stephen@paradisetefl.comhttps://mail.google.com/mail/u/0/?view=cm&fs=1&tf=1&to=stephen@paradisetefl.com
http://paradisetefl.com

**Comment by kzahel** [comment]
The legacy Chrome App is no longer maintained. I've rebuilt JSTorrent from scratch — the new version is ready at **[jstorrent.com](https://jstorrent.com)**

If you run into any issues, please leave feedback!
